### ISSUE TITLE
For older Android versions

### ISSUE THREAD

**Issue by jpggithub** [waelk10/Metronome#1]
On fdroid.org, Metronome requires Android 5.0 or newer.
Is it possible to make it available for older versions of Android?
I use 4.2.2.

**Comment by waelk10** [comment]
Sorry to say, this isn't a current priority and I'm not too sure that I'll
be able to back-port it without losing some of the core functionality and
esthetics, though I'll look into it when I have enough time after finishing
the current update that I'm working on.

**Comment by leoauri** [comment]
That's a shame. I've been waiting for a good metronome and I also use 4.2.2
