### ISSUE TITLE
'tick' sound instead of tone

### ISSUE THREAD

**Issue by anarcat** [waelk10/Metronome#7]
the metronome works very well, but the "tone" sounds is pretty distracting - it sounds too artificial to be comfortable playing with.

other metronomes usually use a little "tick" sound, usually similar to a small cowbell, to implement the sound. best would be to reproduce the sound of an actual metronome, which sound so lovely.

the "practice hub" has a better sounding sound, for example: https://code.google.com/archive/p/music-practice-tools/

**Comment by jpggithub** [comment]
I totally agree. 
You can also find interesting sounds in https://gitlab.com/funkygoby/metronome

**Comment by waelk10** [comment]
I would gladly do this, but that would require re-writing some significant parts of the code, since I don't have much time to add this to the code, I won't be doing it.
In the meantime, I will close this issue, but you're free to open a pull request with the re-factored code if you want.

**Comment by waelk10** [comment]
I want to clarify my previous comment:
If you check the code that is generating the tone, it is also responsible for the timing of the "beeps", hence changing the tone/timbre of the sound will require re-writing major parts of the project, and I honestly just don't have the time to do that.
There is also the whole issue of changing the functionality of the application in case the code is refactored to include this feature.
I won't make any promises, but there is a chance that when I have some free time (in about a few months) I MAY try to implement this functionality, but this doesn't guarantee that I will do so, anyhow, that doesn't stop anyone else from trying to do it and I would gladly merge the pull request for the fix if I get one.
